#if !canImport(ObjectiveC)
import XCTest

extension ThreadExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThreadExtensionsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ThreadExtensionsTests.__allTests__ThreadExtensionsTests),
    ]
}
#endif
